[package]
name = "wordle-solver"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "*"
wordle-solver-data = { path = "data" }

[lib]
crate-type = ["cdylib", "rlib"]
